print("Dime el dorsal del mejor joven futbolista acutal")
dorsal = input()
print("Con el número:", dorsal,"Lamine Yamal!")
Dorsal = input("Dime el dorsal de dinho en el F.C. Barcelona: ")
print("Uso el dorsal: ", Dorsal)